export const api = {
    login: '/auth/login',
    userMe: '/auth/me',
    room: '/room',
    region: '/region',
    course: '/course',
    courseCategory: '/courseCategory',
    addAttachment: '/attachment/upload',
    getAttachment: '/attachment',
    teacher: '/teacher',
    payType: '/payType',
    student: '/student',
    group: '/group',
    client:'/client',
    studentPayment:'/studentPayment',
    reklama:'/reklama',
    cashback : 'cashback',
    debtors:'/student/debtors',
    clientStatus: '/clientStatus',
    appeal : 'appeal',
    toplam : 'toplam',
    teacherSalary : 'teacherSalary',
    teacherSalaryApi : '/teacherSalary',
    salary: '/salary',
    attendance : "/attendance"
};