export const REQUEST_START = 'REQUEST_START';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

export const REQUEST_GET_STUDENTS_BY_GROUP_SUCCESS = "REQUEST_GET_STUDENTS_BY_GROUP_SUCCESS";

export const REQUEST_GET_ATTENDANCE_SUCCESS = 'REQUEST_GET_ATTENDANCE_SUCCESS';
export const REQUEST_GET_DEBTORS_SUCCESS = 'REQUEST_GET_DEBTORS_SUCCESS';
export const REQUEST_SAVE_ROOM_SUCCESS = 'REQUEST_SAVE_ROOM_SUCCESS';
export const REQUEST_GET_ROOM_SUCCESS = "REQUEST_GET_ROOM_SUCCESS";

export const REQUEST_SAVE_CASHBACK_SUCCESS = 'REQUEST_SAVE_CASHBACK_SUCCESS';
export const REQUEST_GET_CASHBACK_SUCCESS = "REQUEST_GET_CASHBACK_SUCCESS";

export const REQUEST_GET_CLIENT_SUCCESS = 'REQUEST_GET_CLIENT_SUCCESS';
export const REQUEST_SAVE_CLIENT_SUCCESS='REQUEST_SAVE_CLIENT_SUCCESS';

export const REQUEST_SAVE_DURATION_TYPE_SUCCESS = 'REQUEST_SAVE_DURATION_TYPE_SUCCESS';
export const REQUEST_GET_DURATION_TYPE_SUCCESS = 'REQUEST_GET_DURATION_TYPE_SUCCESS';

export const REQUEST_SAVE_PAYTYPE_SUCCESS = 'REQUEST_SAVE_PAYTYPE_SUCCESS';
export const REQUEST_GET_PAYTYPE_SUCCESS = "REQUEST_GET_PAYTYPE_SUCCESS";

export const REQUEST_GET_REGION_SUCCESS = 'REQUEST_GET_REGION_SUCCESS';
export const REQUEST_SAVE_REGION_SUCCESS = 'REQUEST_SAVE_REGION_SUCCESS';
export const REQUEST_SEARCH_REGION_SUCCESS = 'REQUEST_SEARCH_REGION_SUCCESS';

export const REQUEST_GET_GROUPS_SUCCESS = 'REQUEST_GET_GROUPS_SUCCESS';
export const REQUEST_GET_GROUPS_FOR_SELECT_SUCCESS = 'REQUEST_GET_GROUPS_FOR_SELECT_SUCCESS';
export const REQUEST_GET_GROUP_SUCCESS = 'REQUEST_GET_GROUP_SUCCESS';
export const REQUEST_GET_GROUP_STUDENTS_SUCCESS = 'REQUEST_GET_GROUP_STUDENTS_SUCCESS';
export const REQUEST_SAVE_GROUP_SUCCESS = 'REQUEST_SAVE_GROUP_SUCCESS';
export const REQUEST_SEARCH_GROUP_SUCCESS = 'REQUEST_SEARCH_GROUP_SUCCESS';

export const REQUEST_GET_COURSES_SUCCESS = 'REQUEST_GET_COURSES_SUCCESS';
export const REQUEST_GET_COURSE_SUCCESS = 'REQUEST_GET_COURSE_SUCCESS';
export const REQUEST_SAVE_COURSE_SUCCESS = 'REQUEST_SAVE_COURSE_SUCCESS';
export const REQUEST_SEARCH_COURSE_SUCCESS = 'REQUEST_SEARCH_COURSE_SUCCESS';


export const REQUEST_GET_PROFESSION_SUCCESS = 'REQUEST_GET_PROFESSION_SUCCESS';
export const REQUEST_SAVE_PROFESSION_SUCCESS = 'REQUEST_SAVE_PROFESSION_SUCCESS';

export const REQUEST_GET_TEST_CATEGORY_SUCCESS = 'REQUEST_GET_TEST_CATEGORY_SUCCESS';
export const REQUEST_SAVE_TEST_CATEGORY_SUCCESS = 'REQUEST_SAVE_TEST_CATEGORY_SUCCESS';

export const REQUEST_GET_REKLAMA_SUCCESS = 'REQUEST_GET_REKLAMA_SUCCESS';
export const REQUEST_SAVE_REKLAMA_SUCCESS = 'REQUEST_SAVE_REKLAMA_SUCCESS';

export const REQUEST_GET_CLIENT_STATUS_LIST_SUCCESS = 'REQUEST_GET_CLIENT_STATUS_LIST_SUCCESS';
export const REQUEST_GET_CLIENT_STATUS_LIST_FOR_SELECT_SUCCESS = 'REQUEST_GET_CLIENT_STATUS_LIST_FOR_SELECT_SUCCESS';
export const REQUEST_SAVE_CLIENT_STATUS_SUCCESS = 'REQUEST_SAVE_CLIENT_STATUS_SUCCESS';

export const REQUEST_GET_TEACHER_SUCCESS = 'REQUEST_GET_TEACHER_SUCCESS';
export const REQUEST_GET_TEACHER_GROUPS_SUCCESS = 'REQUEST_GET_TEACHER_GROUPS_SUCCESS';
export const REQUEST_GET_TEACHERS_SUCCESS = 'REQUEST_GET_TEACHERS_SUCCESS';
export const REQUEST_GET_TEACHERS_FOR_SELECT_SUCCESS = 'REQUEST_GET_TEACHERS_FOR_SELECT_SUCCESS';
export const REQUEST_SAVE_TEACHER_SUCCESS = 'REQUEST_SAVE_TEACHER_SUCCESS';

export const REQUEST_GET_STUDENT_SUCCESS = 'REQUEST_GET_STUDENT_SUCCESS';
export const REQUEST_GET_STUDENTS_SUCCESS = 'REQUEST_GET_STUDENTS_SUCCESS';
export const REQUEST_SAVE_STUDENT_SUCCESS = 'REQUEST_SAVE_STUDENT_SUCCESS';
export const REQUEST_SAVE_STUDENT_STATUS_SUCCESS = 'REQUEST_SAVE_STUDENT_STATUS_SUCCESS';

export const REQUEST_SAVE_COURSE_CATEGORY_SUCCESS = 'REQUEST_SAVE_COURSE_CATEGORY_SUCCESS';
export const REQUEST_GET_COURSE_CATEGORIES_SUCCESS = 'REQUEST_GET_COURSE_CATEGORIES_SUCCESS';
export const REQUEST_GET_COURSE_CATEGORY_SUCCESS = 'REQUEST_GET_COURSE_CATEGORY_SUCCESS';


export const REQUEST_SAVE_TRIAL_CONTACT_TYPE_SUCCESS = 'REQUEST_SAVE_TRIAL_CONTACT_TYPE_SUCCESS';
export const REQUEST_GET_TRIAL_CONTACT_TYPE_SUCCESS = 'REQUEST_GET_TRIAL_CONTACT_TYPE_SUCCESS';

export const REQUEST_ATTACHMENT_SUCCESS = 'REQUEST_ATTACHMENT_SUCCESS';


export const REQUEST_GET_STUDENT_PAYMENT_SUCCESS = 'REQUEST_GET_STUDENT_PAYMENT_SUCCESS';
export const REQUEST_GET_STUDENT_GROUPS_SUCCESS = 'REQUEST_GET_STUDENT_GROUPS_SUCCESS';
export const REQUEST_SAVE_STUDENT_PAYMENT_SUCCESS = 'REQUEST_SAVE_STUDENT_PAYMENT_SUCCESS';
export const REQUEST_GET_STUDENT_PAYMENT_CASHBACKS_SUCCESS = 'REQUEST_GET_STUDENT_PAYMENT_CASHBACKS_SUCCESS';
export const REQUEST_SAVE_STUDENT_PAYMENT_LIST_SUCCESS = 'REQUEST_SAVE_STUDENT_PAYMENT_LIST_SUCCESS'

// START APPEAL TYPES
export const REQUEST_GET_APPEAL_LIST_SUCCESS ='REQUEST_GET_APPEAL_LIST_SUCCESS';
export const REQUEST_GET_APPEAL_SUCCESS ='REQUEST_GET_APPEAL_SUCCESS';
export const REQUEST_SAVE_APPEAL_SUCCESS ='REQUEST_SAVE_APPEAL_SUCCESS';
// FINISH APPEAL TYPES
// START APPEAL TYPES
export const REQUEST_GET_TOPLAM_LIST_SUCCESS ='REQUEST_GET_TOPLAM_LIST_SUCCESS';
export const REQUEST_GET_TOPLAM_SUCCESS ='REQUEST_GET_TOPLAM_SUCCESS';
export const REQUEST_SAVE_TOPLAM_SUCCESS ='REQUEST_SAVE_TOPLAM_SUCCESS';
export const REQUEST_GET_TOPLAM_FOR_SELECT_LIST_SUCCESS ='REQUEST_GET_TOPLAM_FOR_SELECT_LIST_SUCCESS';
// FINISH APPEAL TYPES


// START TEACHER SALARY
export const REQUEST_GIVE_SALARY_SUCCESS ='REQUEST_GIVE_SALARY_SUCCESS';
export const REQUEST_SAVE_TEACHER_SALARY_SUCCESS ='REQUEST_SAVE_TEACHER_SALARY_SUCCESS';
export const REQUEST_GET_LIST_SALARY_SUCCESS ='REQUEST_GET_SALARY_LIST_SUCCESS';

// FINISH TEACHER SALARY


